title: Eleftherios "Lef" Ioannidis
author: Lef Ioannidis
interests: >
  Researcher in Programming Languages (PL) and Verification (Proof Assistants), soon-to-be using Large Language Models (LLMs) to verify programs in Microsoft Research's
  [RiSE group](https://www.microsoft.com/en-us/research/group/research-software-engineering-rise).
bio: >
    I completed my PhD in the University of Pennsylvania advised by [Sebastian Angel](https://www.cis.upenn.edu/~sga001/) and [Steve Zdancewic](https://www.cis.upenn.edu/~stevez/),
    where I developed Domain-Specific Programming Languages (DSLs) to improve the reliability, security and privacy of computer systems, combining techniques from formal verification
    and cryptographic protocols.
    Before starting my PhD I worked in industry as a Software Engineer ([Bridgewater Associates](https://www.bridgewater.com/),
    [Apple](https://www.apple.com/)) and Tech Lead at
    [UnifyID](https://www.rsaconference.com/library/press-release/unifyid-unanimously-named-rsa-conference-2017s-most). I completed by Bachelor's and
    Masters in MIT and my thesis advisors were [Frans Kaashoek](http://people.csail.mit.edu/kaashoek/) and
    [Nickolai Zeldovich](http://people.csail.mit.edu/nickolai/). I am from Thessaloniki, Greece and started my academic career at the Aristotle University of Thessaloniki (AUTH).
email: elefthei@mit.edu
description: Verification, Rocq, LLM, Logic, Ticl, Zippel, Haskell, Zero-knowledge, zkSNARK, Eleftherios, Ioannidis, MIT, Penn
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Eleftherios "Lef" Ioannidis
  tagline: "Programming Languages and Verification Researcher"
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: false # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/images/me2.jpg" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  navigation:
    - title: Publications
      url: "/publications"
    - title: Teaching
      url: "/teaching"
    - title: Resume
      url: "/resume"
  condensed_mobile:
    #- home
    - page
    - post
  # generate social links in footer
  social_links:
    twitter: elefthei
    github:  elefthei
    linkedIn: in/elefthei
    email: elefthei@seas.upenn.edu
    # orcid: "https://orcid.org/0000-0003-2749-797X"
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #gitlab: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
